/**
 * @fileoverview gRPC-Web generated client stub for user
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.28.3
// source: user_profile.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as user_profile_pb from './user_profile_pb'; // proto import: "user_profile.proto"


export class UserServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateUser = new grpcWeb.MethodDescriptor(
    '/user.UserService/CreateUser',
    grpcWeb.MethodType.UNARY,
    user_profile_pb.UserProfile,
    user_profile_pb.UserProfile,
    (request: user_profile_pb.UserProfile) => {
      return request.serializeBinary();
    },
    user_profile_pb.UserProfile.deserializeBinary
  );

  createUser(
    request: user_profile_pb.UserProfile,
    metadata?: grpcWeb.Metadata | null): Promise<user_profile_pb.UserProfile>;

  createUser(
    request: user_profile_pb.UserProfile,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_profile_pb.UserProfile) => void): grpcWeb.ClientReadableStream<user_profile_pb.UserProfile>;

  createUser(
    request: user_profile_pb.UserProfile,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_profile_pb.UserProfile) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.UserService/CreateUser',
        request,
        metadata || {},
        this.methodDescriptorCreateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.UserService/CreateUser',
    request,
    metadata || {},
    this.methodDescriptorCreateUser);
  }

  methodDescriptorUpdateUser = new grpcWeb.MethodDescriptor(
    '/user.UserService/UpdateUser',
    grpcWeb.MethodType.UNARY,
    user_profile_pb.UserProfile,
    user_profile_pb.UserProfile,
    (request: user_profile_pb.UserProfile) => {
      return request.serializeBinary();
    },
    user_profile_pb.UserProfile.deserializeBinary
  );

  updateUser(
    request: user_profile_pb.UserProfile,
    metadata?: grpcWeb.Metadata | null): Promise<user_profile_pb.UserProfile>;

  updateUser(
    request: user_profile_pb.UserProfile,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_profile_pb.UserProfile) => void): grpcWeb.ClientReadableStream<user_profile_pb.UserProfile>;

  updateUser(
    request: user_profile_pb.UserProfile,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_profile_pb.UserProfile) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.UserService/UpdateUser',
        request,
        metadata || {},
        this.methodDescriptorUpdateUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.UserService/UpdateUser',
    request,
    metadata || {},
    this.methodDescriptorUpdateUser);
  }

  methodDescriptorFetchUser = new grpcWeb.MethodDescriptor(
    '/user.UserService/FetchUser',
    grpcWeb.MethodType.UNARY,
    user_profile_pb.UserRequest,
    user_profile_pb.UserProfile,
    (request: user_profile_pb.UserRequest) => {
      return request.serializeBinary();
    },
    user_profile_pb.UserProfile.deserializeBinary
  );

  fetchUser(
    request: user_profile_pb.UserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<user_profile_pb.UserProfile>;

  fetchUser(
    request: user_profile_pb.UserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_profile_pb.UserProfile) => void): grpcWeb.ClientReadableStream<user_profile_pb.UserProfile>;

  fetchUser(
    request: user_profile_pb.UserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_profile_pb.UserProfile) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.UserService/FetchUser',
        request,
        metadata || {},
        this.methodDescriptorFetchUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.UserService/FetchUser',
    request,
    metadata || {},
    this.methodDescriptorFetchUser);
  }

  methodDescriptorListUsers = new grpcWeb.MethodDescriptor(
    '/user.UserService/ListUsers',
    grpcWeb.MethodType.UNARY,
    user_profile_pb.Empty,
    user_profile_pb.UserList,
    (request: user_profile_pb.Empty) => {
      return request.serializeBinary();
    },
    user_profile_pb.UserList.deserializeBinary
  );

  listUsers(
    request: user_profile_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<user_profile_pb.UserList>;

  listUsers(
    request: user_profile_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_profile_pb.UserList) => void): grpcWeb.ClientReadableStream<user_profile_pb.UserList>;

  listUsers(
    request: user_profile_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_profile_pb.UserList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.UserService/ListUsers',
        request,
        metadata || {},
        this.methodDescriptorListUsers,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.UserService/ListUsers',
    request,
    metadata || {},
    this.methodDescriptorListUsers);
  }

}

export class GroupServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateGroup = new grpcWeb.MethodDescriptor(
    '/user.GroupService/CreateGroup',
    grpcWeb.MethodType.UNARY,
    user_profile_pb.Group,
    user_profile_pb.Group,
    (request: user_profile_pb.Group) => {
      return request.serializeBinary();
    },
    user_profile_pb.Group.deserializeBinary
  );

  createGroup(
    request: user_profile_pb.Group,
    metadata?: grpcWeb.Metadata | null): Promise<user_profile_pb.Group>;

  createGroup(
    request: user_profile_pb.Group,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_profile_pb.Group) => void): grpcWeb.ClientReadableStream<user_profile_pb.Group>;

  createGroup(
    request: user_profile_pb.Group,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_profile_pb.Group) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.GroupService/CreateGroup',
        request,
        metadata || {},
        this.methodDescriptorCreateGroup,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.GroupService/CreateGroup',
    request,
    metadata || {},
    this.methodDescriptorCreateGroup);
  }

  methodDescriptorUpdateGroup = new grpcWeb.MethodDescriptor(
    '/user.GroupService/UpdateGroup',
    grpcWeb.MethodType.UNARY,
    user_profile_pb.Group,
    user_profile_pb.Group,
    (request: user_profile_pb.Group) => {
      return request.serializeBinary();
    },
    user_profile_pb.Group.deserializeBinary
  );

  updateGroup(
    request: user_profile_pb.Group,
    metadata?: grpcWeb.Metadata | null): Promise<user_profile_pb.Group>;

  updateGroup(
    request: user_profile_pb.Group,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_profile_pb.Group) => void): grpcWeb.ClientReadableStream<user_profile_pb.Group>;

  updateGroup(
    request: user_profile_pb.Group,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_profile_pb.Group) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.GroupService/UpdateGroup',
        request,
        metadata || {},
        this.methodDescriptorUpdateGroup,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.GroupService/UpdateGroup',
    request,
    metadata || {},
    this.methodDescriptorUpdateGroup);
  }

  methodDescriptorFetchGroup = new grpcWeb.MethodDescriptor(
    '/user.GroupService/FetchGroup',
    grpcWeb.MethodType.UNARY,
    user_profile_pb.GroupRequest,
    user_profile_pb.Group,
    (request: user_profile_pb.GroupRequest) => {
      return request.serializeBinary();
    },
    user_profile_pb.Group.deserializeBinary
  );

  fetchGroup(
    request: user_profile_pb.GroupRequest,
    metadata?: grpcWeb.Metadata | null): Promise<user_profile_pb.Group>;

  fetchGroup(
    request: user_profile_pb.GroupRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_profile_pb.Group) => void): grpcWeb.ClientReadableStream<user_profile_pb.Group>;

  fetchGroup(
    request: user_profile_pb.GroupRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_profile_pb.Group) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.GroupService/FetchGroup',
        request,
        metadata || {},
        this.methodDescriptorFetchGroup,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.GroupService/FetchGroup',
    request,
    metadata || {},
    this.methodDescriptorFetchGroup);
  }

  methodDescriptorListGroups = new grpcWeb.MethodDescriptor(
    '/user.GroupService/ListGroups',
    grpcWeb.MethodType.UNARY,
    user_profile_pb.Empty,
    user_profile_pb.GroupList,
    (request: user_profile_pb.Empty) => {
      return request.serializeBinary();
    },
    user_profile_pb.GroupList.deserializeBinary
  );

  listGroups(
    request: user_profile_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<user_profile_pb.GroupList>;

  listGroups(
    request: user_profile_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: user_profile_pb.GroupList) => void): grpcWeb.ClientReadableStream<user_profile_pb.GroupList>;

  listGroups(
    request: user_profile_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: user_profile_pb.GroupList) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/user.GroupService/ListGroups',
        request,
        metadata || {},
        this.methodDescriptorListGroups,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/user.GroupService/ListGroups',
    request,
    metadata || {},
    this.methodDescriptorListGroups);
  }

}

